import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { AlertCircle, Archive, BellOff, Check, CheckCircle2, ChevronRight, CircleAlert, Clipboard, Clock3, Download, FileText, LoaderCircle, Plus, RefreshCw, RotateCcw, Save, ShieldCheck, Trash2, X } from 'lucide-react'
import { api } from './api'
import type { Incident, IncidentPostmortem, IncidentStatus, PostmortemAction } from './types'

const statusLabel = (status: IncidentStatus) => status === 'open' ? '开放' : status === 'acknowledged' ? '已确认' : status === 'muted' ? '已静默' : '已恢复'
const formatTime = (value?: string) => value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '—'

export function IncidentsView({ openRequest }: { openRequest: (requestId: string) => void }) {
  const [items, setItems] = useState<Incident[]>([]); const [filter, setFilter] = useState<'active' | IncidentStatus | 'all'>('active'); const [selected, setSelected] = useState<Incident | null>(null); const [postmortemIncident, setPostmortemIncident] = useState<Incident | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const loadVersion = useRef(0)
  const load = useCallback(async (quiet = false) => { const version = ++loadVersion.current; if (!quiet) setLoading(true); setError(''); try { const values = await api.incidents(); if (version !== loadVersion.current) return; setItems(values); setSelected(current => current ? values.find(value => value.id === current.id) || null : null) } catch (cause) { if (version === loadVersion.current) setError(cause instanceof Error ? cause.message : '无法读取事故') } finally { if (version === loadVersion.current) setLoading(false) } }, [])
  useEffect(() => { void load(); return () => { loadVersion.current++ } }, [load])
  const visible = useMemo(() => items.filter(item => filter === 'all' || filter === 'active' ? filter === 'all' || item.status !== 'resolved' : item.status === filter), [filter, items])
  const activeCount = items.filter(item => item.status !== 'resolved').length; const criticalCount = items.filter(item => item.status !== 'resolved' && item.severity === 'critical').length
  return <div className="page incidents-page"><section className="page-heading incidents-heading"><div><span className="eyebrow"><CircleAlert/>Incident center</span><h1>把重复故障，收敛成一条清晰时间线。</h1><p>同一 Provider 或主备组在恢复前只保留一条开放事故，失败、验证、人工操作与恢复都会持续追加到时间线。</p></div><button className="secondary" disabled={loading} onClick={() => void load()}><RefreshCw className={loading ? 'spinning' : ''}/>刷新</button></section><div className="incident-safety"><ShieldCheck/><span><strong>事故只保存脱敏事实</strong><small>不会保存 Prompt、API Key、代理凭证或完整供应商响应；关联请求可打开统一请求详情。</small></span></div><section className="incident-summary"><div><span>开放事故</span><strong>{activeCount}</strong><small>包含已确认与静默</small></div><div><span>严重事故</span><strong>{criticalCount}</strong><small>达到连续失败阈值</small></div><div><span>今日恢复</span><strong>{items.filter(item => item.resolvedAt && Date.now() - new Date(item.resolvedAt).getTime() < 86400000).length}</strong><small>最近 24 小时</small></div><div><span>累计事故</span><strong>{items.length}</strong><small>历史事实不会删除</small></div></section><div className="incident-tabs" role="tablist">{([['active','处理中'],['open','开放'],['acknowledged','已确认'],['muted','静默'],['resolved','已恢复'],['all','全部']] as const).map(([value,label]) => <button role="tab" aria-selected={filter === value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)} key={value}>{label}</button>)}</div>{error && <div className="error-banner" role="alert"><AlertCircle/><div><strong>事故读取失败</strong><span>{error}</span></div><button onClick={() => void load()}>重试</button></div>}<section className="incidents-layout"><div className="panel incident-list" aria-busy={loading}>{loading ? [0,1,2].map(value => <div className="incident-card skeleton-card" key={value}/>) : visible.map(item => <button className={`incident-card ${item.severity} ${selected?.id === item.id ? 'active' : ''}`} onClick={() => setSelected(item)} key={item.id}><span className={`incident-status ${item.status}`}>{statusLabel(item.status)}</span><div><strong>{item.title}</strong><small>{item.subjectType === 'group' ? 'Provider Group' : 'Provider'} · {item.subjectName || item.subjectId}</small></div><div className="incident-card-metrics"><span><CircleAlert/>{item.failureCount} 次失败</span><span><Clock3/>{formatTime(item.updatedAt)}</span></div><ChevronRight/></button>)}{!loading && !visible.length && <div className="incident-empty"><CheckCircle2/><strong>当前筛选下没有事故</strong><p>新的失败信号会自动聚合到这里，恢复后保留完整时间线。</p></div>}</div>{selected && <IncidentDetail value={selected} close={() => setSelected(null)} changed={(next) => { setSelected(next); setItems(current => current.map(item => item.id === next.id ? next : item)) }} openRequest={openRequest} openPostmortem={() => setPostmortemIncident(selected)}/>}</section>{postmortemIncident && <PostmortemDrawer incident={postmortemIncident} close={() => setPostmortemIncident(null)}/>}</div>
}

function IncidentDetail({ value, close, changed, openRequest, openPostmortem }: { value: Incident; close: () => void; changed: (value: Incident) => void; openRequest: (id: string) => void; openPostmortem: () => void }) {
  const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [note, setNote] = useState(value.note || '')
  useEffect(() => setNote(value.note || ''), [value.id, value.note])
  const run = async (action: string, operation: () => Promise<Incident>) => { setBusy(action); setError(''); try { changed(await operation()) } catch (cause) { setError(cause instanceof Error ? cause.message : '事故操作失败') } finally { setBusy('') } }
  const timeline = [...(value.timeline || [])].sort((a,b) => new Date(b.at).getTime() - new Date(a.at).getTime())
  return <aside className="panel incident-detail" aria-label={`${value.title} 事故详情`}><header><div><span className={`incident-status ${value.status}`}>{statusLabel(value.status)}</span><h2>{value.title}</h2><small>{value.subjectName || value.subjectId}</small></div><button className="icon-button" aria-label="关闭事故详情" onClick={close}><X/></button></header><div className="incident-detail-scroll"><div className="incident-metrics"><div><span>严重程度</span><strong>{value.severity === 'critical' ? '严重' : '警告'}</strong></div><div><span>失败次数</span><strong>{value.failureCount}</strong></div><div><span>开始时间</span><strong>{formatTime(value.startedAt)}</strong></div><div><span>最近更新</span><strong>{formatTime(value.updatedAt)}</strong></div></div>{error && <div className="form-error" role="alert"><AlertCircle/>{error}</div>}<div className="incident-actions"><button className="primary" disabled={Boolean(busy)} onClick={openPostmortem}><Archive/>事故复盘</button>{value.status === 'open' && <button className="secondary" disabled={Boolean(busy)} onClick={() => void run('ack', () => api.acknowledgeIncident(value.id))}><Check/>{busy === 'ack' ? '处理中' : '确认事故'}</button>}{value.status !== 'resolved' && <button className="secondary" disabled={Boolean(busy)} onClick={() => void run('mute', () => api.muteIncident(value.id, 3600))}><BellOff/>{busy === 'mute' ? '处理中' : '静默 1 小时'}</button>}{value.status !== 'resolved' ? <button className="danger-button" disabled={Boolean(busy)} onClick={() => void run('close', () => api.closeIncident(value.id))}><CheckCircle2/>{busy === 'close' ? '处理中' : '手动关闭'}</button> : <button className="secondary" disabled={Boolean(busy)} onClick={() => void run('reopen', () => api.reopenIncident(value.id))}><RotateCcw/>{busy === 'reopen' ? '处理中' : '重新打开'}</button>}</div><section className="incident-note"><header><FileText/><strong>事故备注</strong></header><textarea rows={3} value={note} maxLength={4096} placeholder="记录判断、临时措施或后续行动…" onChange={event => setNote(event.target.value)}/><button className="secondary" disabled={Boolean(busy) || note === (value.note || '')} onClick={() => void run('note', () => api.noteIncident(value.id, note))}>{busy === 'note' ? <LoaderCircle className="spinning"/> : <Save/>}保存备注</button></section><section className="incident-timeline"><header><Clock3/><strong>事故时间线</strong><span>{timeline.length} 条记录</span></header>{timeline.map(entry => <article key={entry.id}><i className={entry.type.includes('recover') || entry.type.includes('resolved') ? 'success' : entry.type.includes('manual') ? 'manual' : 'failure'}/><div><time>{formatTime(entry.at)}</time><strong>{entry.message}</strong>{entry.requestId && <button onClick={() => openRequest(entry.requestId)}>请求 {entry.requestId}</button>}</div></article>)}</section></div></aside>
}

function PostmortemDrawer({ incident, close }: { incident: Incident; close: () => void }) {
  const [value, setValue] = useState<IncidentPostmortem | null>(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [message, setMessage] = useState('')
  const initialized = useRef(false)
  const loadVersion = useRef(0)
  const refreshTimer = useRef<number | null>(null)
  const [rootCause, setRootCause] = useState(''), [mitigation, setMitigation] = useState(''), [owner, setOwner] = useState(''), [actions, setActions] = useState<PostmortemAction[]>([])
  const apply = (next: IncidentPostmortem) => { setValue(next); setRootCause(next.rootCause || ''); setMitigation(next.mitigation || ''); setOwner(next.owner || ''); setActions(next.actions || []) }
  const load = useCallback(async () => { const version = ++loadVersion.current; setLoading(true); setError(''); try { const next = initialized.current ? await api.incidentPostmortem(incident.id) : await api.createIncidentPostmortem(incident.id); if (version !== loadVersion.current) return; initialized.current = true; apply(next) } catch (cause) { if (version === loadVersion.current) setError(cause instanceof Error ? cause.message : '复盘读取失败') } finally { if (version === loadVersion.current) setLoading(false) } }, [incident.id])
  useEffect(() => { initialized.current = false; setValue(null); void load(); return () => { loadVersion.current++; if (refreshTimer.current != null) window.clearTimeout(refreshTimer.current) } }, [load])
  const run = async (key: string, operation: () => Promise<IncidentPostmortem>, success: string) => { if (busy) return; setBusy(key); setError(''); try { apply(await operation()); setMessage(success); if (refreshTimer.current != null) window.clearTimeout(refreshTimer.current); refreshTimer.current = window.setTimeout(() => void load(), 2500) } catch (cause) { setError(cause instanceof Error ? cause.message : '复盘操作失败') } finally { setBusy('') } }
  const markdown = async (download: boolean) => { setBusy(download ? 'download' : 'copy'); try { const text = await api.incidentPostmortemMarkdown(incident.id); if (download) { const url = URL.createObjectURL(new Blob([text], {type:'text/markdown;charset=utf-8'})); const anchor = document.createElement('a'); anchor.href=url; anchor.download=`incident-${incident.id}-postmortem.md`; anchor.click(); URL.revokeObjectURL(url); setMessage('Markdown 已下载') } else { await navigator.clipboard.writeText(text); setMessage('Markdown 已复制') } } catch (cause) { setError(cause instanceof Error ? cause.message : 'Markdown 生成失败') } finally { setBusy('') } }
  const updateAction = (index: number, patch: Partial<PostmortemAction>) => setActions(current => current.map((item, itemIndex) => itemIndex === index ? {...item,...patch} : item))
  const duration = value ? value.durationSeconds < 60 ? `${value.durationSeconds} 秒` : value.durationSeconds < 3600 ? `${Math.round(value.durationSeconds/60)} 分钟` : `${(value.durationSeconds/3600).toFixed(1)} 小时` : '—'
  const readonly = value?.status === 'completed'
  return <div className="overlay postmortem-overlay"><button className="overlay-scrim" aria-label="关闭事故复盘" onClick={close}/><aside className="drawer postmortem-drawer" role="dialog" aria-modal="true" aria-labelledby="postmortem-title"><header className="postmortem-header"><div><span><Archive/>{value?.status === 'completed' ? '已完成' : '草稿'}</span><h2 id="postmortem-title">{incident.title}</h2><small>{incident.subjectName || incident.subjectId} · {duration}</small></div><button className="icon-button" aria-label="关闭" onClick={close}><X/></button></header>
    <div className="postmortem-scroll">{loading ? <div className="postmortem-loading"><LoaderCircle className="spinning"/>正在封存事故证据</div> : error && !value ? <div className="error-banner"><AlertCircle/><div><strong>复盘未生成</strong><span>{error}</span></div><button onClick={() => void load()}>重试</button></div> : value && <>{message && <div className="toast-inline success" role="status"><CheckCircle2/>{message}</div>}{error && <div className="form-error" role="alert"><AlertCircle/>{error}</div>}
      <section className="postmortem-seal"><Archive/><div><strong>事实证据已封存</strong><span>以下内容来自生成时的事故快照，后续日志清理不会改变报告。</span></div></section>
      <section className="postmortem-facts"><div><span>严重程度</span><strong>{value.severity === 'critical' ? '严重' : '警告'}</strong></div><div><span>失败次数</span><strong>{value.failureCount}</strong></div><div><span>关联请求</span><strong>{value.requestIds.length}</strong></div><div><span>恢复结论</span><strong>{value.recoverySummary}</strong></div></section>
      <section className="postmortem-evidence"><header><Clock3/><strong>快照时间线</strong><span>{value.timeline.length} 条</span></header>{value.timeline.map(entry => <article key={entry.id}><time>{formatTime(entry.at)}</time><strong>{entry.message}</strong>{entry.requestId && <code>{entry.requestId}</code>}</article>)}</section>
      <section className="postmortem-editor"><header><FileText/><div><strong>人工结论</strong><span>{readonly ? '已完成，重新打开后可编辑' : '事实不会被修改，这里记录判断与行动'}</span></div></header><label><span>根因</span><textarea rows={4} maxLength={8192} disabled={readonly} value={rootCause} onChange={event => setRootCause(event.target.value)}/></label><label><span>处置总结</span><textarea rows={4} maxLength={8192} disabled={readonly} value={mitigation} onChange={event => setMitigation(event.target.value)}/></label><label><span>复盘负责人</span><input maxLength={256} disabled={readonly} value={owner} onChange={event => setOwner(event.target.value)}/></label><div className="postmortem-actions"><header><strong>后续行动</strong>{!readonly && <button onClick={() => setActions(current => [...current,{text:'',owner:'',completed:false}])}><Plus/>添加</button>}</header>{actions.map((action,index) => <div key={index}><input type="checkbox" disabled={readonly} checked={action.completed} onChange={event => updateAction(index,{completed:event.target.checked})}/><input aria-label={`行动 ${index+1}`} maxLength={2048} disabled={readonly} placeholder="具体行动" value={action.text} onChange={event => updateAction(index,{text:event.target.value})}/><input aria-label={`行动 ${index+1} 负责人`} maxLength={256} disabled={readonly} placeholder="负责人" value={action.owner || ''} onChange={event => updateAction(index,{owner:event.target.value})}/>{!readonly && <button aria-label={`删除行动 ${index+1}`} onClick={() => setActions(current => current.filter((_,itemIndex)=>itemIndex!==index))}><Trash2/></button>}</div>)}</div></section>
    </>}</div><footer className="postmortem-footer"><div><button className="secondary" disabled={!!busy || !value} onClick={() => void markdown(false)}>{busy === 'copy' ? <LoaderCircle className="spinning"/> : <Clipboard/>}复制 Markdown</button><button className="secondary" disabled={!!busy || !value} onClick={() => void markdown(true)}>{busy === 'download' ? <LoaderCircle className="spinning"/> : <Download/>}下载</button></div>{value && (readonly ? <button className="primary" disabled={!!busy} onClick={() => void run('reopen', () => api.reopenIncidentPostmortem(incident.id), '复盘已重新打开')}>{busy === 'reopen' ? <LoaderCircle className="spinning"/> : <RotateCcw/>}重新打开</button> : <><button className="secondary" disabled={!!busy || actions.some(action => !action.text.trim())} onClick={() => void run('save', () => api.saveIncidentPostmortem(incident.id,{rootCause,mitigation,owner,actions}), '复盘草稿已保存')}>{busy === 'save' ? <LoaderCircle className="spinning"/> : <Save/>}保存草稿</button><button className="primary" disabled={!!busy || actions.some(action => !action.text.trim())} onClick={() => void run('complete', async () => { await api.saveIncidentPostmortem(incident.id,{rootCause,mitigation,owner,actions}); return api.completeIncidentPostmortem(incident.id) }, '事故复盘已完成')}>{busy === 'complete' ? <LoaderCircle className="spinning"/> : <CheckCircle2/>}标记完成</button></>)}</footer></aside></div>
}
