import { useCallback, useEffect, useRef, useState } from 'react'
import { AlertCircle, ArrowRight, BellRing, Bot, CheckCircle2, FlaskConical, GitBranch, LoaderCircle, Pencil, Plus, RefreshCw, Save, ShieldCheck, Trash2, X } from 'lucide-react'
import { api } from './api'
import { confirmAction } from './ConfirmDialog'
import { Select } from './Select'
import { useDelayedRefresh } from './useDelayedRefresh'
import type { NotificationChannel, NotificationChannelWrite, NotificationMessageType, NotificationRoutes } from './types'

const routeMeta: Array<[NotificationMessageType,string,string]> = [
  ['incident_opened','新事故','事故首次打开时'],['incident_recovered','事故恢复','事故达到恢复条件时'],['reliability_alert','可靠性告警','Provider 指标越过阈值时'],['reliability_recovered','可靠性恢复','指标恢复并满足连续成功时'],['reliability_digest','定时摘要','每日可靠性摘要'],['job_notification','任务通知','测活结果、恢复与聚合通知'],
]
const emptyRoutes = Object.fromEntries(routeMeta.map(([key]) => [key,''])) as Record<NotificationMessageType,string>

export function NotificationRoutingView() {
  const [channels,setChannels]=useState<NotificationChannel[]>([]), [routes,setRoutes]=useState<NotificationRoutes>({routes:emptyRoutes}), [loading,setLoading]=useState(true), [busy,setBusy]=useState(''), [error,setError]=useState(''), [message,setMessage]=useState(''), [editing,setEditing]=useState<NotificationChannel|'new'|null>(null)
  const loadVersion=useRef(0)
  const load=useCallback(async(quiet=false)=>{const version=++loadVersion.current;if(!quiet)setLoading(true);setError('');try{const [nextChannels,nextRoutes]=await Promise.all([api.notificationChannels(),api.notificationRoutes()]);if(version!==loadVersion.current)return;setChannels(nextChannels);setRoutes({ ...nextRoutes, routes:{...emptyRoutes,...nextRoutes.routes} })}catch(cause){if(version===loadVersion.current)setError(cause instanceof Error?cause.message:'通知路由读取失败')}finally{if(version===loadVersion.current)setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(!message)return;const timer=window.setTimeout(()=>setMessage(''),4000);return()=>window.clearTimeout(timer)},[message])
  const refreshAfter=useDelayedRefresh(()=>load(true))
  const run=async<T,>(key:string,operation:()=>Promise<T>,success:string,apply?:(value:T)=>void)=>{if(busy)return false;setBusy(key);setError('');try{const value=await operation();apply?.(value);setMessage(success);void refreshAfter();return true}catch(cause){setError(cause instanceof Error?cause.message:'通知路由操作失败');return false}finally{setBusy('')}}
  const routeCount=Object.values(routes.routes).filter(Boolean).length
  const channelName=(id:string)=>channels.find(channel=>channel.id===id)?.name||'全局默认机器人'
  const saveRoutes=()=>void run('routes',()=>api.saveNotificationRoutes(routes),'通知路由已保存',next=>setRoutes({ ...next, routes:{...emptyRoutes,...next.routes} }))
  const remove=(channel:NotificationChannel)=>{void confirmAction({title:'删除通知渠道',message:`删除通知渠道“${channel.name}”？`,detail:'引用它的消息类型将回退到全局默认机器人。',confirmLabel:'删除渠道',tone:'danger',action:async()=>{await run(`${channel.id}:delete`,()=>api.deleteNotificationChannel(channel.id),`${channel.name} 已删除`,()=>{setChannels(current=>current.filter(item=>item.id!==channel.id));setRoutes(current=>({ ...current,routes:Object.fromEntries(Object.entries(current.routes).map(([kind,id])=>[kind,id===channel.id?'':id])) as NotificationRoutes['routes'] }))})}})}
  const toggle=(channel:NotificationChannel)=>void run(`${channel.id}:toggle`,()=>api.updateNotificationChannel(channel.id,{name:channel.name,description:channel.description,type:'dingtalk',enabled:!channel.enabled}),`${channel.name} 已${channel.enabled?'停用':'启用'}`,next=>setChannels(current=>current.map(item=>item.id===next.id?next:item)))
  return <div className="page notification-routing-page"><section className="page-heading notification-routing-heading"><div><span className="eyebrow"><GitBranch/>Notification routing</span><h1>让每类消息，抵达正确的人。</h1><p>事故、恢复、可靠性告警、摘要和任务通知可以使用独立钉钉渠道；专用渠道不可用时自动回退默认机器人。</p></div><div><button className="secondary" disabled={loading} onClick={()=>void load()}><RefreshCw className={loading?'spinning':''}/>刷新</button><button className="primary" onClick={()=>setEditing('new')}><Plus/>新增渠道</button></div></section>
    <section className="notification-routing-summary"><div><span>加密渠道</span><strong>{channels.length}</strong><small>{channels.filter(c=>c.enabled).length} 个启用</small></div><div><span>专用路由</span><strong>{routeCount}</strong><small>{6-routeCount} 类使用默认</small></div><div><span>回退策略</span><strong>Default</strong><small>失败时不重复群发</small></div></section>
    <section className="notification-routing-safety"><ShieldCheck/><div><strong>Webhook 始终留在服务端</strong><span>浏览器只看到掩码；路由事件记录渠道 ID 和回退原因，不记录地址或 Token。</span></div></section>
    {error&&<div className="error-banner" role="alert"><AlertCircle/><div><strong>通知路由操作失败</strong><span>{error}</span></div><button onClick={()=>void load()}>重试</button></div>}{message&&<div className="toast-inline success" role="status"><CheckCircle2/>{message}</div>}
    <section className="panel notification-route-board"><header><div><BellRing/><span><strong>消息分流轨道</strong><small>空目标表示继续使用设置页中的全局默认机器人</small></span></div><button className="primary" disabled={!!busy} onClick={saveRoutes}>{busy==='routes'?<LoaderCircle className="spinning"/>:<Save/>}{busy==='routes'?'保存中':'保存路由'}</button></header><div>{routeMeta.map(([kind,label,detail])=><article key={kind}><div className="notification-route-source"><i/><span><strong>{label}</strong><small>{detail}</small></span></div><ArrowRight/><label><span>目标渠道</span><Select aria-label={`${label}目标渠道`} value={routes.routes[kind]||''} onChange={event=>setRoutes(current=>({...current,routes:{...current.routes,[kind]:event.target.value}}))}><option value="">全局默认机器人</option>{channels.map(channel=><option value={channel.id} disabled={!channel.enabled} key={channel.id}>{channel.name}{channel.enabled?'':'（已停用）'}</option>)}</Select><small>{channelName(routes.routes[kind])}</small></label></article>)}</div></section>
    <section className="notification-channel-section"><header><div><Bot/><span><strong>加密渠道库</strong><small>渠道可被多种消息复用</small></span></div></header><div className="notification-channel-grid">{loading&&!channels.length?[0,1].map(i=><div className="panel notification-channel-card skeleton-card" key={i}/>):channels.map(channel=><article className={`panel notification-channel-card ${channel.enabled?'':'disabled'}`} key={channel.id}><header><div className="notification-channel-icon"><Bot/></div><div><strong>{channel.name}</strong><small>{channel.description||'钉钉机器人渠道'}</small></div><span>{channel.enabled?'启用':'停用'}</span></header><dl><div><dt>类型</dt><dd>DingTalk</dd></div><div><dt>Webhook</dt><dd>{channel.maskedWebhook||'已加密'}</dd></div><div><dt>路由引用</dt><dd>{Object.values(routes.routes).filter(id=>id===channel.id).length} 类消息</dd></div></dl><footer><button disabled={!!busy||!channel.enabled} onClick={()=>void run(`${channel.id}:test`,()=>api.testNotificationChannel(channel.id),`${channel.name} 测试成功`)}>{busy===`${channel.id}:test`?<LoaderCircle className="spinning"/>:<FlaskConical/>}测试</button><button onClick={()=>setEditing(channel)} disabled={!!busy}><Pencil/>编辑</button><button onClick={()=>toggle(channel)} disabled={!!busy}>{channel.enabled?'停用':'启用'}</button><button className="danger-button" onClick={()=>remove(channel)} disabled={!!busy}><Trash2/>删除</button></footer></article>)}</div>{!loading&&!channels.length&&<div className="panel notification-channel-empty"><Bot/><strong>还没有专用通知渠道</strong><span>创建渠道后，可把不同消息分流到对应群组。</span><button className="primary" onClick={()=>setEditing('new')}><Plus/>创建第一个渠道</button></div>}</section>
    {editing&&<NotificationChannelDialog value={editing==='new'?null:editing} busy={busy==='channel-save'} close={()=>setEditing(null)} save={async body=>{const success=await run('channel-save',()=>editing==='new'?api.createNotificationChannel(body):api.updateNotificationChannel(editing.id,body),editing==='new'?'通知渠道已创建':'通知渠道已更新',next=>setChannels(current=>[...current.filter(item=>item.id!==next.id),next]));if(success)setEditing(null)}}/>}</div>
}

function NotificationChannelDialog({value,busy,close,save}:{value:NotificationChannel|null;busy:boolean;close:()=>void;save:(body:NotificationChannelWrite)=>Promise<void>}){
  const [name,setName]=useState(value?.name||''),[id,setID]=useState(value?.id||''),[description,setDescription]=useState(value?.description||''),[webhookUrl,setWebhook]=useState(''),[enabled,setEnabled]=useState(value?.enabled??true)
  return <div className="scenario-dialog-overlay"><button className="scenario-dialog-scrim" disabled={busy} aria-label="关闭通知渠道编辑" onClick={close}/><section className="scenario-dialog notification-channel-dialog" role="dialog" aria-modal="true" aria-labelledby="notification-channel-dialog-title"><header><div><span>Encrypted notification channel</span><h2 id="notification-channel-dialog-title">{value?.name||'新增通知渠道'}</h2></div><button className="icon-button" disabled={busy} aria-label="关闭" onClick={close}><X/></button></header><div className="scenario-dialog-body"><div className="notification-channel-guard"><ShieldCheck/>Webhook 保存后使用 AES-GCM 加密，明文不会返回浏览器。</div><div className="field-grid"><label className="field"><span>渠道名称 *</span><input autoFocus maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>渠道 ID</span><input disabled={Boolean(value)} value={id} placeholder="自动生成" onChange={e=>setID(e.target.value.toLowerCase())}/></label></div><label className="field"><span>用途说明</span><textarea rows={3} maxLength={2048} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="field"><span>{value?'替换 Webhook（留空则保留）':'Webhook *'}</span><input type="url" spellCheck={false} placeholder="https://oapi.dingtalk.com/robot/send?access_token=…" value={webhookUrl} onChange={e=>setWebhook(e.target.value)}/></label><label className="scenario-enabled"><span><strong>启用此渠道</strong><small>停用后引用它的通知会回退全局默认机器人。</small></span><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><i/></label></div><footer><button className="secondary" disabled={busy} onClick={close}>取消</button><button className="primary" disabled={busy||!name.trim()||(!value&&!webhookUrl.trim())} onClick={()=>void save({id:id||undefined,name:name.trim(),description:description.trim(),type:'dingtalk',enabled,webhookUrl:webhookUrl.trim()||undefined})}>{busy?<LoaderCircle className="spinning"/>:<Save/>}{busy?'保存中':'保存渠道'}</button></footer></section></div>
}
